### ISSUE TITLE
Implement NavBar  (UI)

### ISSUE THREAD

**Issue by rhedwan** [zuri-training/AuthWiki_Team9#12]

**Comment by rhedwan** [comment]
@Christian-03 **Please endeavor to share your progress here.**

**Comment by Christian-03** [comment]
![navigation bar](https://user-images.githubusercontent.com/70984807/181226376-afe6abd5-46f1-49db-8261-ee9844807b4a.jpg)
I'm done with the navigation bar. I'd like to get your feedback.

**Comment by rhedwan** [comment]
@Christian-03 send your pull request

**Comment by Christian-03** [comment]
Alright
