### ISSUE TITLE
Design Login Page

### ISSUE THREAD

**Issue by rhedwan** [zuri-training/AuthWiki_Team9#50]

**Comment by oribipoloamina** [comment]
@miracle-E @rhedwan Log In and Registration task is done. https://www.figma.com/file/ZiuCDL7seXKfkdzfCHXtkG/Auth_Wiki?node-id=3%3A2

**Comment by oribipoloamina** [comment]
![Log In](https://user-images.githubusercontent.com/105321582/181372864-66776adc-5010-414b-8f93-bbf3ac47981d.png)
