### ISSUE TITLE
Landing Page Design (Hi-Fi)

### ISSUE THREAD

**Issue by miracle-E** [zuri-training/AuthWiki_Team9#70]
Assigned to @miracle-E

**Comment by rhedwan** [comment]
@miracle-E who worked on this

**Comment by miracle-E** [comment]
@miracle-E

**Comment by miracle-E** [comment]
Link to the landing page: https://www.figma.com/file/ZiuCDL7seXKfkdzfCHXtkG/Team_9_AUTH_WIKI?node-id=47%3A10
