### ISSUE TITLE
"Examples/Doc" Page Design 

### ISSUE THREAD

**Issue by miracle-E** [zuri-training/AuthWiki_Team9#88]
Assigned to @oribipoloamina

**Comment by rhedwan** [comment]
Nice one

**Comment by oribipoloamina** [comment]
@miracle-E @rhedwan done

**Comment by rhedwan** [comment]
@oribipoloamina send a screenshot and the link

**Comment by oribipoloamina** [comment]
https://www.figma.com/file/ZiuCDL7seXKfkdzfCHXtkG/Team_9_AUTH_WIKI?node-id=3%3A2

**Comment by oribipoloamina** [comment]
@rhedwan
