### ISSUE TITLE
User profile page design

### ISSUE THREAD

**Issue by miracle-E** [zuri-training/AuthWiki_Team9#93]
Assigned to @bamigbolaios16

**Comment by bamigbolaios16** [comment]
https://www.figma.com/file/ZiuCDL7seXKfkdzfCHXtkG/Team_9_AUTH_WIKI?node-id=769%3A2704

**Comment by miracle-E** [comment]
@rhedwan Kindly reassign to @miracle-E

**Comment by miracle-E** [comment]
Link to Design: https://www.figma.com/file/USDw28ms1nZClxuyTjZHMY/Team_9_AUTH_WIKI-(Copy)?node-id=1023%3A3124

**Comment by rhedwan** [comment]
@miracle-E  done
